"""10-B2b: risk sizing for the five short templates (MACD/RSI bearish divergence, double top,
head-and-shoulders top, Chan third sell) and Chan third buy.

Risk distance = |actual next-open fill - the template's own initial stop frozen at the signal|;
direction only signs the order quantity. Expected numbers below are hand arithmetic
(capital 10000, fee/slippage 0 unless stated), never generated by the code under test.
"""
from decimal import Decimal

import pytest
from fastapi.testclient import TestClient

import _10b2b_cases as c
import cutie_backtesting_provider as p
from strategy_position_sizing import POSITION_SIZE_KEYS

TOOLS = tuple(c.CASES)
RISK = dict(position_size_risk_pct=1, position_size_qty_step=0.001)
REPORT_KEY = dict(macd_bearish_divergence='divergence', rsi_bearish_divergence='divergence',
                  double_top='top_pattern', head_shoulders='top_pattern', chan_3sell='chan', chan_3buy='chan')


def fills(body):
    return body['raw_report']['position_sizing']['fills']


def signed_qty(trade):
    return Decimal(trade['qty']) * (-1 if trade['side'] == 'short' else 1)


@pytest.mark.parametrize('name,label', [(n, v) for n in c.GOLDEN_VARIANTS for v in c.GOLDEN_VARIANTS[n]])
def test_omitted_sizing_keys_match_aa5f9e6_bytes(name, label, monkeypatch, tmp_path):
    golden = (c.GOLDEN_DIR / f'{name}.{label}.json').read_text()
    body = c.post(monkeypatch, tmp_path, name, c.GOLDEN_VARIANTS[name][label])
    assert body['result_status'] == 'success'
    assert c.canonical(body) + '\n' == golden


# name -> (fill, frozen stop, signed qty). 1% of equity 10000 = 100 risked, step 0.001:
#  bearish divergence: H2 High 122 * 1.001 = 122.122 (float 122.12199999999999); fill bar24 open 100;
#                      100 / 22.122 = 4.5203.. -> 4.520, short => -4.520
#  double top:         last top High 100 * 1.001 = 100.1; fill bar54 open 89; 100 / 11.1 = 9.0090.. -> -9.009
#  head-shoulders:     right shoulder High 99 * 1.001 = 99.099; fill 81; 100 / 18.099 = 5.5251.. -> -5.525
#  chan third sell:    pullback High 126 * 1.001 = 126.126 (float 126.12599999999999); fill bar13 open 115;
#                      100 / 11.126 = 8.9879.. -> -8.987
#  chan third buy:     pullback Low 114 * 0.999 = 113.886; fill bar13 open 125; 100 / 11.114 = 8.9976.. -> +8.997
HAND = {
    'macd_bearish_divergence': ('100.0', '122.12199999999999', '-4.520'),
    'rsi_bearish_divergence': ('100.0', '122.12199999999999', '-4.520'),
    'double_top': ('89.0', '100.1', '-9.009'),
    'head_shoulders': ('81.0', '99.099', '-5.525'),
    'chan_3sell': ('115.0', '126.12599999999999', '-8.987'),
    'chan_3buy': ('125.0', '113.886', '8.997'),
}


@pytest.mark.parametrize('name', TOOLS)
def test_risk_quantity_hand_calculated(name, monkeypatch, tmp_path):
    body = c.post(monkeypatch, tmp_path, name, RISK)
    assert body['result_status'] == 'success', body
    fill, stop, qty = HAND[name]
    assert [(f['fill_price'], f['initial_stop'], f['qty']) for f in fills(body)] == [(fill, stop, qty.lstrip('-'))]
    assert [signed_qty(t) for t in body['trades']] == [Decimal(qty)]
    assert [Decimal(t['entry_price']) for t in body['trades']] == [Decimal(fill)]
    assert body['raw_report']['position_sizing']['rejections'] == []
    assert body['assumptions']['position_sizing']['initial_stop'] == 'template_frozen_signal_stop_actual_fill_distance'


def gapped(name):
    data = c.CASES[name][0]()
    if name in ('macd_bearish_divergence', 'rsi_bearish_divergence'):
        data.iloc[24, :2] = [122.2, 123]          # open at/above 122.122
    elif name in ('double_top', 'head_shoulders'):
        data.iloc[54, :4] = [101, 102, 79, 89]    # open above 100.1 / 99.099
    elif name == 'chan_3sell':
        data.iloc[13, :2] = [130, 131]            # open above 126.126
    else:
        data.iloc[13, :4] = [110, 126, 109, 125]  # open below 113.886
    return data


@pytest.mark.parametrize('name', TOOLS)
def test_gap_past_frozen_stop_skips_before_sizing(name, monkeypatch, tmp_path):
    body = c.post(monkeypatch, tmp_path, name, RISK, data=gapped(name))
    assert body['result_status'] == 'success', body
    skipped = body['raw_report'][REPORT_KEY[name]]['skipped_entries']
    side = 'below' if name == 'chan_3buy' else 'above'
    assert skipped[0]['reason'] == f'entry_open_at_or_{side}_frozen_stop'
    assert body['trades'] == []
    assert body['raw_report']['position_sizing'] == dict(
        compound=False, qty_step='0.001', fills=[], rejections=[])


@pytest.mark.parametrize('name', TOOLS)
def test_quantity_below_step_fails_closed(name, monkeypatch, tmp_path):
    body = c.post(monkeypatch, tmp_path, name, dict(position_size_risk_pct=0.0001, position_size_qty_step=1))
    assert body['result_status'] == 'success', body
    assert body['trades'] == []
    reasons = [r['reason'] for r in body['raw_report']['position_sizing']['rejections']]
    assert reasons and set(reasons) == {'quantity_below_step'}


@pytest.mark.parametrize('name', TOOLS)
def test_user_stop_rejected_before_fetch(name, monkeypatch, tmp_path):
    body = c.post(monkeypatch, tmp_path, name, {**RISK, 'stop_loss_pct': 3},
                  fetch=lambda *a, **k: pytest.fail('rejected request fetched data'))
    assert body['result_status'] == 'failed' and body['error_type'] == 'INVALID_PARAMS'
    assert 'conflict' in body['error_message'] or 'mutually exclusive' in body['error_message']


# Leverage 3, chan third sell (fill 115, stop 126.126). Risk 29%: 2900 / 11.126 = 260.6507.. -> 260.650.
#  margin = 260.65 * 115 / 3 = 9991.58333..;  fee 10 bps cost = 260.65 * 115 * 0.001 = 29.97475
#  fee 0:  margin 9991.58 <= 10000 -> filled.  fee 10: 9991.58 + 29.97 = 10021.56 > 10000 -> rejected.
def test_leverage3_short_reserves_margin_and_fees(monkeypatch, tmp_path):
    params = dict(position_size_risk_pct=29, position_size_qty_step=0.001, leverage=3)
    body = c.post(monkeypatch, tmp_path, 'chan_3sell', params)
    assert body['result_status'] == 'success', body
    [fill] = fills(body)
    assert (fill['fill_price'], fill['qty']) == ('115.0', '260.650')
    assert Decimal(fill['margin']) == Decimal('260.650') * Decimal('115.0') / 3
    assert [signed_qty(t) for t in body['trades']] == [Decimal('-260.650')]
    fee = c.post(monkeypatch, tmp_path, 'chan_3sell', params, fee='10')
    assert fee['trades'] == []
    assert [r['reason'] for r in fee['raw_report']['position_sizing']['rejections']] == ['insufficient_funds_after_fees']


def liquidation_frame():
    data = c.CASES['chan_3sell'][0]()
    data.iloc[14, :4] = [160, 161, 159, 160]   # gaps over stop 126.126 and liquidation 115 * 4/3
    return data


# Leverage 3 short fill 115: liquidation = 115 * (1 + 1/3) = 153.333.. (mmr 0); bar14 opens 160 => gap.
# Sized qty 8.987 (1%): margin_lost = 8.987 * 115 / 3 = 344.50166..;
# loss_beyond_margin = 8.987 * (160 - 153.333..) = 59.91333..
def test_leverage3_short_liquidation_detail_matches_unsized_basis(monkeypatch, tmp_path):
    sized = c.post(monkeypatch, tmp_path, 'chan_3sell', {**RISK, 'leverage': 3}, data=liquidation_frame())
    plain = c.post(monkeypatch, tmp_path, 'chan_3sell', {'leverage': 3}, data=liquidation_frame())
    assert sized['result_status'] == plain['result_status'] == 'success', (sized, plain)
    a, b = sized['raw_report']['isolated_risk'], plain['raw_report']['isolated_risk']
    assert a['leverage'] == b['leverage'] == 3
    assert a['liquidation_count'] == b['liquidation_count'] == 1
    assert a['liquidation_gap_count'] == b['liquidation_gap_count'] == 1
    [da], [db] = a['liquidations'], b['liquidations']
    for key in ('seq', 'liquidation_price', 'fill_price', 'liquidation_gap'):
        assert da[key] == db[key], key
    liq = Decimal(115) * 4 / 3
    assert abs(Decimal(da['liquidation_price']) - liq) < Decimal('1e-6')
    assert Decimal(da['fill_price']) == 160
    qty = Decimal('8.987')
    assert abs(Decimal(da['margin_lost']) - qty * 115 / 3) < Decimal('1e-6')
    assert abs(Decimal(da['loss_beyond_margin']) - qty * (160 - liq)) < Decimal('1e-6')
    assert [signed_qty(t) for t in sized['trades']] == [-qty]


def test_six_templates_left_pending_list_and_others_still_reject(monkeypatch):
    monkeypatch.setattr(p, 'AUTH_TOKEN', '')
    monkeypatch.setattr(p, '_fetch_ohlcv', lambda *a, **k: pytest.fail('pending tool fetched data'))
    wired = {'local.backtesting_py.' + n for n in TOOLS}
    assert wired.isdisjoint(p.POSITION_SIZING_PENDING_TOOLS)
    assert wired <= p.POSITION_SIZING_TEMPLATE_STOP_TOOLS
    for tool in wired:
        assert POSITION_SIZE_KEYS <= set(p.TOOL_SPECS[tool]['param_schema_properties']), tool
    assert len(p.POSITION_SIZING_PENDING_TOOLS) == 14
    client = TestClient(p.app)
    for tool in sorted(p.POSITION_SIZING_PENDING_TOOLS):
        assert POSITION_SIZE_KEYS.isdisjoint(p.TOOL_SPECS[tool]['param_schema_properties']), tool
        request = dict(run_id='10b2b', provider_tool_id=tool, provider_params=dict(RISK, stop_loss_pct=2),
                       symbol='BTCUSDT', market='spot', timeframe='1h', start_at=1767225600,
                       end_at=1767312000, initial_capital='10000', fee_bps='0', slippage_bps='0')
        body = client.post('/cutie/backtest', json={'backtest': request}).json()
        assert body['raw_report']['position_sizing'] == {
            'rejections': [{'reason': 'position sizing is not wired to this template yet'}]}, tool
