"""10-B2c: risk sizing for the six long candle templates, double bottom and inverse head-and-shoulders.

Risk distance = |actual next-open fill - the template's own initial stop frozen at the signal|
(PatternEntry.stop / BottomEntry.stop). These templates reject every pattern-exit key, so a user
stop_loss_pct is rejected before any fetch. Expected numbers below are hand arithmetic
(capital 10000, fee/slippage 0), never generated by the code under test.
"""
from decimal import Decimal

import pytest
from fastapi.testclient import TestClient

import _10b2c_cases as c
import cutie_backtesting_provider as p
from strategy_position_sizing import POSITION_SIZE_KEYS

TOOLS = tuple(c.CASES)
RISK = dict(position_size_risk_pct=1, position_size_qty_step=0.001)
REPORT_KEY = {**{n: 'candle_pattern' for n in c.CANDLE}, **{n: 'bottom_pattern' for n in c.BOTTOM}}
REMAINING_10B2D = frozenset('local.backtesting_py.' + n for n in (
    'opening_range_breakout', 'asia_range_breakout', 'calendar_schedule', 'red_streak_rsi',
    'us_open_momentum', 'cme_weekend_gap'))


def fills(body):
    return body['raw_report']['position_sizing']['fills']


@pytest.mark.parametrize('name,label', [(n, v) for n in c.GOLDEN_VARIANTS for v in c.GOLDEN_VARIANTS[n]])
def test_omitted_sizing_keys_match_5d0f9ac_bytes(name, label, monkeypatch, tmp_path):
    golden = (c.GOLDEN_DIR / f'{name}.{label}.json').read_text()
    body = c.post(monkeypatch, tmp_path, name, c.GOLDEN_VARIANTS[name][label])
    assert body['result_status'] == 'success'
    assert c.canonical(body) + '\n' == golden


# name -> (fill, frozen stop, qty). 1% of equity 10000 = 100 risked, step 0.001:
#  engulfing:   stop = min(Low bar24 98, bar25 97) * 0.999 = 96.903; fill bar26 open 106 (signal close 104);
#               100 / (106 - 96.903) = 100 / 9.097 = 10.9926.. -> 10.992
#  pin bar:     stop = pin Low 97 * 0.999 = 96.903; fill 106 (signal close 103) -> 10.992
#  morning star / three soldiers / doji / inside bar: designated anchor Low 97 * 0.999 = 96.903;
#               fill bar26 open 110 (signal closes 106 / 107 / 108 / 109);
#               100 / (110 - 96.903) = 100 / 13.097 = 7.6353.. -> 7.635
#  double bottom:  last bottom Low 100 * 0.999 = 99.9; fill bar54 open 111; 100 / 11.1 = 9.0090.. -> 9.009
#  inverse H&S:    right shoulder Low 101 * 0.999 = 100.899; fill 119; 100 / 18.101 = 5.5245.. -> 5.524
HAND = {
    'bullish_engulfing': ('106.0', '96.903', '10.992'),
    'hammer_pin_bar': ('106.0', '96.903', '10.992'),
    'morning_star': ('110.0', '96.903', '7.635'),
    'three_white_soldiers': ('110.0', '96.903', '7.635'),
    'bullish_doji_reversal': ('110.0', '96.903', '7.635'),
    'inside_bar_breakout': ('110.0', '96.903', '7.635'),
    'double_bottom': ('111.0', '99.9', '9.009'),
    'inverse_head_shoulders': ('119.0', '100.899', '5.524'),
}


@pytest.mark.parametrize('name', TOOLS)
def test_risk_quantity_hand_calculated(name, monkeypatch, tmp_path):
    body = c.post(monkeypatch, tmp_path, name, RISK)
    assert body['result_status'] == 'success', body
    fill, stop, qty = HAND[name]
    assert [(f['fill_price'], f['initial_stop'], f['qty']) for f in fills(body)] == [(fill, stop, qty)]
    assert [(t['side'], Decimal(t['qty']), Decimal(t['entry_price'])) for t in body['trades']] == [
        ('long', Decimal(qty), Decimal(fill))]
    assert body['raw_report']['position_sizing']['rejections'] == []
    assert body['assumptions']['position_sizing']['initial_stop'] == 'template_frozen_signal_stop_actual_fill_distance'


# The bottom fixtures fill at an open equal to the signal close (111 / 119); move the fill-bar open
# so the distance can only come from the actual fill:
#  double bottom: bar54 [112, 113, 111, 112]: 100 / (112 - 99.9) = 100 / 12.1 = 8.2644.. -> 8.264 (111 gives 9.009)
#  inverse H&S:   bar54 [120, 121, 119, 120]: 100 / (120 - 100.899) = 100 / 19.101 = 5.2353.. -> 5.235 (119 gives 5.524)
@pytest.mark.parametrize('name,row,expected', [
    ('double_bottom', [112, 113, 111, 112], ('112.0', '99.9', '8.264')),
    ('inverse_head_shoulders', [120, 121, 119, 120], ('120.0', '100.899', '5.235'))])
def test_bottom_distance_uses_actual_fill_not_signal_close(name, row, expected, monkeypatch, tmp_path):
    data = c.CASES[name]()
    data.iloc[54, :4] = row
    body = c.post(monkeypatch, tmp_path, name, RISK, data=data)
    assert body['result_status'] == 'success', body
    assert [(f['fill_price'], f['initial_stop'], f['qty']) for f in fills(body)] == [expected]
    assert [Decimal(t['qty']) for t in body['trades']] == [Decimal(expected[2])]


def gapped(name):
    data = c.CASES[name]()
    if name in c.CANDLE:
        data.iloc[26, :4] = [96.8, 110, 96.8, 106]   # open below 96.903
    elif name == 'double_bottom':
        data.iloc[54, :4] = [99.5, 112, 99, 111]     # open below 99.9
    else:
        data.iloc[54, :4] = [100.5, 120, 100, 119]   # open below 100.899
    return data


@pytest.mark.parametrize('name', TOOLS)
def test_gap_past_frozen_stop_skips_before_sizing(name, monkeypatch, tmp_path):
    body = c.post(monkeypatch, tmp_path, name, RISK, data=gapped(name))
    assert body['result_status'] == 'success', body
    skipped = body['raw_report'][REPORT_KEY[name]]['skipped_entries']
    assert [s['reason'] for s in skipped] == ['entry_open_at_or_below_frozen_stop']
    assert body['trades'] == []
    assert body['raw_report']['position_sizing'] == dict(
        compound=False, qty_step='0.001', fills=[], rejections=[])


@pytest.mark.parametrize('name', TOOLS)
def test_quantity_below_step_fails_closed(name, monkeypatch, tmp_path):
    body = c.post(monkeypatch, tmp_path, name, dict(position_size_risk_pct=0.0001, position_size_qty_step=1))
    assert body['result_status'] == 'success', body
    assert body['trades'] == []
    reasons = [r['reason'] for r in body['raw_report']['position_sizing']['rejections']]
    assert reasons and set(reasons) == {'quantity_below_step'}


@pytest.mark.parametrize('name', TOOLS)
def test_user_stop_rejected_before_fetch(name, monkeypatch, tmp_path):
    body = c.post(monkeypatch, tmp_path, name, {**RISK, 'stop_loss_pct': 3},
                  fetch=lambda *a, **k: pytest.fail('rejected request fetched data'))
    assert body['result_status'] == 'failed' and body['error_type'] == 'INVALID_PARAMS'
    assert 'mutually exclusive' in body['error_message']


def test_eight_templates_left_pending_list_and_remaining_six_still_reject(monkeypatch):
    monkeypatch.setattr(p, 'AUTH_TOKEN', '')
    monkeypatch.setattr(p, '_fetch_ohlcv', lambda *a, **k: pytest.fail('pending tool fetched data'))
    wired = {'local.backtesting_py.' + n for n in TOOLS}
    assert len(wired) == 8
    assert wired.isdisjoint(p.POSITION_SIZING_PENDING_TOOLS)
    assert wired <= p.POSITION_SIZING_TEMPLATE_STOP_TOOLS
    for tool in wired:
        assert POSITION_SIZE_KEYS <= set(p.TOOL_SPECS[tool]['param_schema_properties']), tool
    assert p.POSITION_SIZING_PENDING_TOOLS == REMAINING_10B2D
    client = TestClient(p.app)
    for tool in sorted(REMAINING_10B2D):
        assert POSITION_SIZE_KEYS.isdisjoint(p.TOOL_SPECS[tool]['param_schema_properties']), tool
        request = dict(run_id='10b2c', provider_tool_id=tool, provider_params=dict(RISK, stop_loss_pct=2),
                       symbol='BTCUSDT', market='spot', timeframe='1h', start_at=1767225600,
                       end_at=1767312000, initial_capital='10000', fee_bps='0', slippage_bps='0')
        body = client.post('/cutie/backtest', json={'backtest': request}).json()
        assert body['raw_report']['position_sizing'] == {
            'rejections': [{'reason': 'position sizing is not wired to this template yet'}]}, tool
