"""Independent rational goldens, causal prefixes and registered provider execution."""
from pathlib import Path
import json
import sys

import numpy as np
import pandas as pd
import pytest
from backtesting import Backtest
from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import cutie_backtesting_provider as p
from strategy_divergence import divergence_signals, macd_values
from strategy_time_layer import TimeConfig, TimeContext
from test_time_layer import DEFAULTS as TIME_OFF
from test_entry_filters import DEFAULTS as FILTER_OFF

NAMES = ('macd_bullish_divergence', 'rsi_bullish_divergence')


def hand_params(name):
    values = dict(swing_n=2)
    if name.startswith('macd'):
        values.update(fast=2, slow=3, signal=2)
    else:
        values.update(rsi_period=2)
    return values


def hand_frame(size=64):
    # L1=13 (Low79, Close80), L2=21 (Low78, Close90), gap8; N2 => confirms23.
    # EMA alpha2/3 and 1/2; DEA alpha2/3. At22 DIF<=DEA; at23 DIF>DEA.
    closes = [100.]*12+[90,80,90,95,96,96,94,92,91,90,89,94,94,110,110,110]
    closes += [110.]*(size-len(closes))
    data = pd.DataFrame(dict(Open=closes, High=np.array(closes)+1, Low=np.array(closes)-1,
                             Close=closes, Volume=100.),
                        index=pd.date_range('2026-01-01', periods=size, freq='h'))
    data.iloc[21, 2] = 78.
    data.iloc[24, 0] = 100.
    data.iloc[24, 1] = 101.
    return data


def run(name, data=None, *, warm=0, **values):
    data = hand_frame() if data is None else data
    cls = p.TOOL_SPECS['local.backtesting_py.'+name]['build']({**hand_params(name), **values})['strategy']
    cls._warmup_bars = warm
    cls._warmup_cols = {c: data[c].iloc[:warm].to_numpy() for c in p._WARMUP_COLUMNS}
    main = data.iloc[warm:].copy()
    if cls._time_config is not None:
        cls._time_context = TimeContext.build(cls._time_config, '1h', main.index)
    return Backtest(main, cls, cash=100000, exclusive_orders=True, finalize_trades=True).run()


def facts(data=None, *, kind='macd', values=None, dif=None, dea=None, **config):
    data = hand_frame() if data is None else data
    # Test doubles are scalar, fixed indicator facts, never generated by subject.
    if values is None:
        values = [40.]*max(24,len(data))
        values[13], values[21] = (10., 20.) if kind=='rsi' else (-3., -1.)
    if dif is None:
        dif = [-1.]*len(data)
        dif[23:] = [1.]*(len(data)-23)
    dea = [0.]*len(data) if dea is None else dea
    return divergence_signals(*(data[c].to_numpy() for c in ('High','Low','Close')), values,
                              kind=kind, n=2, dif=dif, dea=dea, **config)


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('warm', [0, 10])
def test_hand_low_bar_values_and_next_open(name, warm):
    result = run(name, warm=warm)
    entries = result['_strategy'].divergence_report['entries']
    assert len(entries) == 1
    assert entries[0] == dict(setup=0, entry_bar=24-warm, entry_price=100.,
                             frozen_stop=pytest.approx(77.922), frozen_target=pytest.approx(144.156))
    setup = result['_strategy'].divergence_report['setups'][0]
    assert (setup['l1_index'], setup['l2_index'], setup['confirmed_at'], setup['signal_bar']) == (13,21,23,23)
    assert (setup['l1_price'], setup['l2_price']) == (79.,78.)
    if name.startswith('macd'):
        assert setup['l1_indicator'] == pytest.approx(-55/18)
        assert setup['l2_indicator'] == pytest.approx(-.5218417318138364)
        assert result['_trades'][['EntryBar','ExitBar']].values.tolist() == [[24-warm,28-warm]]
    else:
        assert setup['l1_indicator'] == 0
        assert setup['l2_indicator'] == pytest.approx(7.511737089201878)
        assert result['_trades'][['EntryBar','ExitBar']].values.tolist() == [[24-warm,25-warm]]


@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_unconfirmed_second_low_never_signals_and_prefix_is_causal(kind):
    data = hand_frame()
    dif = [-1.]*len(data)
    dif[22] = 1.  # Early cross one bar before L2's right N bars have closed.
    dif[24:] = [1.]*(len(data)-24)
    full, _ = facts(data, kind=kind, dif=dif)
    assert all(full[i] is None for i in (21,22))
    assert full[23 if kind=='rsi' else 24] is not None
    for end in (21,22,23,24,25,29):
        part, _ = facts(data.iloc[:end], kind=kind, dif=dif[:end])
        assert part == full[:end]
    changed = data.copy()
    changed.iloc[25:, :4] = [500,501,499,500]
    assert facts(changed, kind=kind, dif=dif)[0][:25] == full[:25]


@pytest.mark.parametrize('name', NAMES)
def test_registered_short_prefix_cannot_enter(name):
    assert run(name, hand_frame().iloc[:23])['_trades'].empty
    assert run(name, hand_frame().iloc[:24])['_trades'].empty  # no next Open
    assert run(name, hand_frame().iloc[:25])['_strategy'].divergence_report['entries'][0]['entry_bar'] == 24


@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_samples_low_bar_not_confirmation_bar(kind):
    values = [0.]*64
    values[13],values[21] = 10.,20.
    values[15],values[23] = 90.,1.  # confirmation samples would reverse divergence
    assert facts(kind=kind, values=values)[0][23] is not None


@pytest.mark.parametrize('low,valid', [(78.,True),(79.,False),(80.,False)])
@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_price_direction_strict(low,valid,kind):
    data=hand_frame();data.iloc[21,2]=low
    assert (facts(data,kind=kind)[0][23] is not None) is valid


@pytest.mark.parametrize('second,valid', [(9.,False),(10.,False),(11.,True)])
@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_indicator_direction_strict(second,valid,kind):
    values=[40.]*64;values[13],values[21]=10.,second
    assert (facts(kind=kind,values=values)[0][23] is not None) is valid


@pytest.mark.parametrize('first,valid', [(34.999,True),(35.,False),(35.001,False)])
def test_rsi_threshold_strict(first,valid):
    values=[40.]*64;values[13],values[21]=first,36.
    assert (facts(kind='rsi',values=values)[0][23] is not None) is valid


@pytest.mark.parametrize('lo,hi,valid', [(8,8,True),(9,60,False),(5,7,False)])
def test_gap_bounds_inclusive(lo,hi,valid):
    assert (facts(min_gap=lo,max_gap=hi)[0][23] is not None) is valid


def test_adjacent_low_only():
    data=hand_frame();data.iloc[17,2]=78.5
    assert not any(facts(data)[0])  # gaps4 to new adjacent lows fail minimum5


def test_close_invalidation_before_later_macd_cross():
    data=hand_frame();data.iloc[24,:4]=[80,81,76,77]
    dif=[-1.]*64;dif[25:]=[1.]*39
    signals,setups=facts(data,dif=dif)
    assert not any(signals)
    assert setups[0]['status']=='invalidated_close' and setups[0]['invalidated_at']==24
    data.iloc[24,:4]=[80,81,77,77.922]  # equality does not invalidate
    assert facts(data,dif=dif)[0][25] is not None


def test_new_confirmed_low_invalidates_waiting_macd():
    data=hand_frame();data.iloc[24,:4]=[90,91,78.5,90]
    data.iloc[25,:4]=[90,91,89,90];data.iloc[26,:4]=[90,91,89,90]
    dif=[-1.]*64;dif[27:]=[1.]*37
    signals,setups=facts(data,dif=dif)
    assert not any(signals)
    assert setups[0]['status']=='invalidated_new_low' and setups[0]['invalidated_at']==26


@pytest.mark.parametrize('compare', ['dif','hist'])
def test_macd_comparison_modes(compare):
    report=run(NAMES[0],compare=compare)['_strategy'].divergence_report
    assert len(report['entries'])==1 and report['compare']==compare
    if compare=='hist':
        assert report['setups'][0]['l1_indicator']==pytest.approx(-35/27)
        assert report['setups'][0]['l2_indicator']==pytest.approx(-.0848256276919781)


def test_independent_indicator_goldens_and_causal_tail():
    dif,dea,hist=macd_values([100.,90.,80.,90.],2,3,2)
    np.testing.assert_allclose(dif,[0,-5/3,-55/18,-65/108],atol=1e-12)
    np.testing.assert_allclose(dea,[0,-10/9,-65/27,-65/54],atol=1e-12)
    np.testing.assert_allclose(hist,[0,-10/9,-35/27,65/54],atol=1e-12)
    np.testing.assert_allclose(p._rsi_series([100.,90.,80.,90.],2),[50,0,0,50])
    data=hand_frame()
    before=macd_values(data.Close,2,3,2)
    data.iloc[25:,3]=10000
    after=macd_values(data.Close,2,3,2)
    for a,b in zip(before,after):np.testing.assert_array_equal(a[:25],b[:25])


@pytest.mark.parametrize('name', NAMES)
def test_2r_uses_actual_fill_and_remains_frozen(name):
    data=hand_frame();data.iloc[25,:4]=[110,144.,109,110]
    data.iloc[26,:4]=[110,145.,109,110]
    # signal close94 would target126.156; actual100 gives144.156.
    result=run(name,data,**({'rsi_exit_above':100} if name.startswith('rsi') else {}))
    assert result['_trades'][['EntryBar','ExitBar']].values.tolist()==[[24,27]]
    assert result['_strategy'].divergence_report['exits']==[dict(reason='take_profit',decision_bar=26)]
    assert result['_strategy'].divergence_report['entries'][0]['frozen_target']==pytest.approx(144.156)


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('opening,valid', [(77.9,False),(77.922,False),(77.923,True)])
def test_next_open_gap_is_skipped_once(name,opening,valid):
    data=hand_frame();data.iloc[24,:4]=[opening,101.,77.,94.]
    report=run(name,data)['_strategy'].divergence_report
    assert bool(report['entries']) is valid
    assert bool(report['skipped_entries']) is not valid
    if not valid:assert report['skipped_entries'][0]['reason']=='entry_open_at_or_below_frozen_stop'


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('stop,expiry,reason', [(True,True,'stop_loss'),(False,True,'time_expiry'),(False,False,'take_profit')])
def test_same_bar_exit_priority(name,stop,expiry,reason):
    data=hand_frame();data.iloc[24,:4]=[100,150,77. if stop else 90.,94]
    result=run(name,data,**({'max_holding_bars':1,'risk_layer_enabled':True} if expiry else {}))
    assert result['_trades'][['EntryBar','ExitBar']].values.tolist()==[[24,25]]
    assert result['_strategy'].divergence_report['exits'][0]['reason']==reason


@pytest.mark.parametrize('name', NAMES)
def test_filters_block_pair_without_delayed_entry(name):
    # EMA500 has insufficient history on this short frame, so it blocks every entry.
    report=run(name,filter_layer_enabled=True,filter_ema_enabled=True,filter_ema_period=500)['_strategy'].divergence_report
    assert not report['entries'] and report['setups'][0]['signal_bar']==23
    assert not run(name,time_layer_enabled=True,time_session_start='01:00',time_session_end='02:00')['_strategy'].divergence_report['entries']


@pytest.mark.parametrize('name', NAMES)
def test_default_off_engine_bytes_equal(name):
    a=run(name);b=run(name,**TIME_OFF,**FILTER_OFF)
    pd.testing.assert_frame_equal(a['_trades'],b['_trades'])
    pd.testing.assert_frame_equal(a['_equity_curve'],b['_equity_curve'])
    assert a['_strategy'].divergence_report==b['_strategy'].divergence_report


def request(name,params,data=None):
    data=hand_frame() if data is None else data
    return dict(backtest=dict(run_id='9t4',provider_tool_id='local.backtesting_py.'+name,
        provider_params=params,symbol='BTCUSDT',market='spot',timeframe='1h',
        start_at=int(data.index[0].timestamp()),end_at=int(data.index[-1].timestamp())+3600,
        initial_capital='10000',fee_bps='0',slippage_bps='0'))


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('values', [dict(direction='short'),dict(direction='both'),dict(swing_n=True),dict(swing_n=2.0),
    dict(min_gap_bars=10,max_gap_bars=5),dict(swing_n=0),dict(min_gap_bars='5'),
    dict(stop_loss_pct=1),dict(take_profit_pct=2),dict(risk_layer_enabled=True,trailing_stop_pct=1)])
def test_invalid_params_rejected_before_fetch(name,values,monkeypatch):
    monkeypatch.setattr(p,'AUTH_TOKEN','')
    monkeypatch.setattr(p,'_fetch_ohlcv',lambda *a:pytest.fail('invalid request fetched'))
    monkeypatch.setattr(p,'_fetch_template_warmup',lambda *a:pytest.fail('invalid request fetched warmup'))
    assert TestClient(p.app).post('/cutie/backtest',json=request(name,values)).json()['error_type']=='INVALID_PARAMS'
    with pytest.raises(ValueError,match='INVALID_PARAMS'):p.TOOL_SPECS['local.backtesting_py.'+name]['build'](values)


@pytest.mark.parametrize('name,values', [(NAMES[0],dict(fast=3,slow=3)),(NAMES[0],dict(compare='bad')),
    (NAMES[0],dict(signal=2.0)),(NAMES[1],dict(rsi_period=2.0)),(NAMES[1],dict(rsi_first_below=80,rsi_exit_above=70))])
def test_indicator_validation(name,values):
    with pytest.raises(ValueError,match='INVALID_PARAMS'):p.TOOL_SPECS['local.backtesting_py.'+name]['build'](values)


@pytest.mark.parametrize('name', NAMES)
def test_http_raw_details_and_frozen_result_v2_keys(name,monkeypatch,tmp_path):
    data=hand_frame()
    monkeypatch.setattr(p,'AUTH_TOKEN','')
    monkeypatch.setattr(p,'REPORTS_DIR',tmp_path)
    monkeypatch.setattr(p,'_fetch_ohlcv',lambda *a:data.copy())
    requested = []
    def warmup(*args):
        requested.append(args[5])
        return data.iloc[:0].copy()
    monkeypatch.setattr(p,'_fetch_template_warmup',warmup)
    monkeypatch.setattr(Backtest,'plot',lambda *a,**kw:None)
    result=TestClient(p.app).post('/cutie/backtest',json=request(name,hand_params(name))).json()
    assert result['result_status']=='success',result
    assert requested == [76 if name.startswith('macd') else 71]
    assert len(result['trades'])==1
    assert result['raw_report']['divergence']['setups'][0]['l2_index']==21
    assert result['raw_report']['divergence']['entries'][0]['frozen_target']==pytest.approx(144.156)
    assert result['assumptions']['divergence_execution']['indicator_sample']=='swing_low_bar'
    # Independent frozen contract baseline, not a key set derived from new response.
    assert set(result['metrics'])=={'total_return','max_drawdown','trade_count'}
    assert set(result['trades'][0])=={'seq','opened_at','closed_at','side','qty','entry_price','exit_price','fee','slippage','pnl'}
    for node in ('metrics','equity_curve','trades','data_manifest'):
        assert 'divergence' not in str(result[node])


@pytest.mark.parametrize('gap,valid', [(4,False),(5,True),(60,True),(61,False)])
@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_default_gap_endpoints_hand_sequence(gap,valid,kind):
    size=gap+15
    low=[99.]*size;low[10],low[10+gap]=90.,89.
    values=[40.]*size;values[10],values[10+gap]=10.,20.
    dif=[-1.]*size;dif[11+gap:]=[1.]*(size-11-gap)
    signals,_=divergence_signals([101.]*size,low,[100.]*size,values,
        kind=kind,n=1,dif=dif,dea=[0.]*size)
    assert (signals[11+gap] is not None) is valid


@pytest.mark.parametrize('name', NAMES)
def test_underwarmed_first_low_cannot_arm(name):
    # MACD indicator warmup slow3*3+signal2+1=12; RSI period2*3+1=7.
    # Move our first swing into the underwarmed prefix; later L2 stays eligible.
    first=10 if name.startswith('macd') else 5
    data=hand_frame().iloc[13-first:].copy()
    assert not run(name,data)['_strategy'].divergence_report['entries']


@pytest.mark.parametrize('name', NAMES)
def test_time_flatten_beats_target(name):
    data=hand_frame();data.iloc[24,1]=150.
    result=run(name,data,time_layer_enabled=True,time_flatten_at='01:00')
    # Flatten clock: bar24's close reaches01:00; entry Open00:00 exists first.
    assert result['_strategy'].divergence_report['exits'][0]['reason']=='time_expiry'
    assert result['_trades'][['EntryBar','ExitBar']].values.tolist()==[[24,25]]


def test_rsi_exit_threshold_strict_and_next_open(monkeypatch):
    values=[50.]*64;values[13],values[21]=10.,20.
    values[24],values[25]=70.,71.
    monkeypatch.setattr(p,'_rsi_series',lambda *a:np.array(values))
    result=run(NAMES[1])
    assert result['_trades'][['EntryBar','ExitBar']].values.tolist()==[[24,26]]
    assert result['_strategy'].divergence_report['exits']==[dict(reason='rsi_exit',decision_bar=25)]


@pytest.mark.parametrize('name', NAMES)
def test_http_off_bytes_and_gap_reason(name,monkeypatch,tmp_path):
    data=hand_frame()
    monkeypatch.setattr(p,'AUTH_TOKEN','')
    monkeypatch.setattr(p,'REPORTS_DIR',tmp_path)
    monkeypatch.setattr(p,'_fetch_ohlcv',lambda *a:data.copy())
    monkeypatch.setattr(p,'_fetch_template_warmup',lambda *a:data.iloc[:0].copy())
    monkeypatch.setattr(Backtest,'plot',lambda *a,**kw:None)
    client=TestClient(p.app)
    original=client.post('/cutie/backtest',json=request(name,hand_params(name))).json()
    explicit=client.post('/cutie/backtest',json=request(name,{**hand_params(name),**TIME_OFF,**FILTER_OFF})).json()
    for key in ('schema_version','metrics','trades','equity_curve','data_manifest','assumptions','raw_report'):
        assert json.dumps(original[key],sort_keys=True,separators=(',',':'))==json.dumps(explicit[key],sort_keys=True,separators=(',',':')),key
    data.iloc[24,0]=77.9
    gap=client.post('/cutie/backtest',json=request(name,hand_params(name))).json()
    assert gap['result_status']=='success' and not gap['trades']
    assert gap['raw_report']['divergence']['skipped_entries'][0]['reason']=='entry_open_at_or_below_frozen_stop'
