"""10-B2d: risk sizing for ORB, Asia range, calendar schedule, red streak RSI, US open momentum and
CME weekend gap; the pending list is empty afterwards.

Risk distance = |actual next-open fill - the stop that actually governs the trade|:
  ORB / Asia      opposite side of the range frozen before the signal;
  calendar        signal close * (1 -/+ stop_loss_pct), frozen at the signal (none when disabled);
  red streak      signal close * (1 - stop), frozen at the signal (default 3% group);
  US open         nearer of the window stop frozen at the signal and the optional user stop;
  CME gap         intrinsic 2% (or the user stop) from the shared fill-time risk state.
Expected numbers are hand arithmetic (capital 10000, fee/slippage 0), never generated by the code.
"""
from decimal import Decimal

import pytest

import _10b2d_cases as c
import cutie_backtesting_provider as p
from strategy_position_sizing import POSITION_SIZE_KEYS

RISK = dict(position_size_risk_pct=1, position_size_qty_step=0.001)


def sizing(body):
    return body['raw_report']['position_sizing']


def signed_qty(trade):
    return Decimal(trade['qty']) * (-1 if trade['side'] == 'short' else 1)


@pytest.mark.parametrize('name,label', [(n, v) for n in c.GOLDEN_VARIANTS for v in c.GOLDEN_VARIANTS[n]])
def test_omitted_sizing_keys_match_1f5b8dc_bytes(name, label, monkeypatch, tmp_path):
    golden = (c.GOLDEN_DIR / f'{name}.{label}.json').read_text()
    params, side = c.GOLDEN_VARIANTS[name][label]
    body = c.post(monkeypatch, tmp_path, name, params, side=side)
    assert body['result_status'] == 'success'
    assert body['trades']
    assert c.canonical(body) + '\n' == golden


def calendar_fill_101():
    data = c.frame('calendar_schedule')
    data.iloc[2] = [101, 102, 99, 100, 1]  # fill open 101; signal close 100 stays the stop anchor
    return data


def calendar_short_fill_99():
    data = c.frame('calendar_schedule')
    data.iloc[2] = [99, 101, 98, 100, 1]
    return data


# id -> (template, extra params, data factory or None, side, fill, frozen stop, signed qty). 1% of 10000 = 100.
HAND = {
    # range 110/90; long signal close 111 fills 112: 100 / (112 - 90) = 4.5454.. -> 4.545
    'orb_long': ('opening_range_breakout', {}, None, 'long', '112.0', '90.0', '4.545'),
    # mirrored: short fills 88 against frozen range high 110: 100 / 22 -> 4.545, sold
    'orb_short': ('opening_range_breakout', dict(direction='short'), None, 'short', '88.0', '110.0', '-4.545'),
    'asia_long': ('asia_range_breakout', {}, None, 'long', '112.0', '90.0', '4.545'),
    'asia_short': ('asia_range_breakout', dict(direction='short'), None, 'short', '88.0', '110.0', '-4.545'),
    # default 3% frozen at signal close 100 -> 97; fill 101: 100 / 4 = 25 (a fill-based stop 97.97 gives 33.003)
    'calendar_long': ('calendar_schedule', {}, calendar_fill_101, 'long', '101.0', '97.0', '25.000'),
    # short: 100 * 1.03 = 103; fill 99: 100 / 4 = 25, sold
    'calendar_short': ('calendar_schedule', dict(direction='short'), calendar_short_fill_99, 'long',
                       '99.0', '103.0', '-25.000'),
    # signal close 92 * 0.97 = 89.24; fill 93: 100 / 3.76 = 26.5957.. -> 26.595 (fill-based 90.21 gives 35.842)
    'red_streak_default': ('red_streak_rsi', {}, None, 'long', '93.0', '89.24', '26.595'),
    # user 2%: 92 * 0.98 = 90.16; 100 / 2.84 = 35.2112.. -> 35.211
    'red_streak_user_stop': ('red_streak_rsi', dict(stop_loss_pct=2), None, 'long', '93.0', '90.16', '35.211'),
    # window 13:30-14:00 Low 98, fill 14:00 open 100: 100 / 2 = 50
    'us_open_window_only': ('us_open_momentum', {}, None, 'long', '100.0', '98.0', '50'),
    # both stops: user 100 * 0.985 = 98.5 is nearer than window 98 and triggers first: 100 / 1.5 -> 66.666
    'us_open_user_nearer': ('us_open_momentum', dict(stop_loss_pct=1.5), None, 'long', '100.0', '98.5', '66.666'),
    # both stops: user 100 * 0.97 = 97 is farther than window 98: window governs, 100 / 2 = 50
    'us_open_window_nearer': ('us_open_momentum', dict(stop_loss_pct=3), None, 'long', '100.0', '98.0', '50'),
    # intrinsic 2% at fill 99 -> 97.02: 100 / 1.98 = 50.5050.. -> 50.505
    'cme_default': ('cme_weekend_gap', {}, None, 'long', '99.0', '97.02', '50.505'),
    # user 1% at fill 99 -> 98.01; risk 0.5% = 50: 50 / 0.99 = 50.5050.. -> 50.505 (default 2% would give 25.252)
    'cme_user_stop': ('cme_weekend_gap', dict(stop_loss_pct=1, position_size_risk_pct=0.5), None, 'long',
                      '99.0', '98.01', '50.505'),
}


@pytest.mark.parametrize('case', sorted(HAND))
def test_risk_quantity_hand_calculated(case, monkeypatch, tmp_path):
    name, extra, factory, side, fill, stop, qty = HAND[case]
    data = factory() if factory else None
    body = c.post(monkeypatch, tmp_path, name, {**RISK, **extra}, data=data, side=side)
    assert body['result_status'] == 'success', body.get('error_message')
    report = sizing(body)
    assert report['rejections'] == []
    [record] = report['fills']
    assert Decimal(record['fill_price']) == Decimal(fill)
    assert Decimal(record['initial_stop']) == Decimal(stop)
    assert Decimal(record['qty']) == abs(Decimal(qty))
    assert [signed_qty(t) for t in body['trades']] == [Decimal(qty)]


def test_us_open_sizes_against_the_stop_that_exits_first(monkeypatch, tmp_path):
    # User stop 98.5 (nearer) and window stop 98 both live; a bar with Low 98.4 hits only the user stop.
    data = c.frame('us_open_momentum')
    data.loc['2026-03-09 14:15', ['Open', 'High', 'Low', 'Close']] = [100, 100.5, 98.4, 99]
    body = c.post(monkeypatch, tmp_path, 'us_open_momentum', {**RISK, 'stop_loss_pct': 1.5}, data=data)
    assert body['result_status'] == 'success', body.get('error_message')
    assert body['raw_report']['us_open_momentum']['exits'][0]['reason'] == 'stop_loss'
    assert Decimal(sizing(body)['fills'][0]['initial_stop']) == Decimal('98.5')


def test_calendar_without_any_stop_rejects_entry(monkeypatch, tmp_path):
    # P-LOW1 moved this combination to the pre-fetch validation (test_plow1); the fill hook stays as the
    # backstop, so bypass the validation gate to keep pinning it.
    monkeypatch.setattr(p, '_sizing_template_initial_stop', lambda *a, **k: True)
    body = c.post(monkeypatch, tmp_path, 'calendar_schedule', {**RISK, 'calendar_stop_enabled': False})
    assert body['result_status'] == 'success', body.get('error_message')
    assert body['trades'] == []
    report = sizing(body)
    assert report['fills'] == []
    assert [r['reason'] for r in report['rejections']] == ['missing_initial_stop']


def test_calendar_gap_guard_precedes_sizing(monkeypatch, tmp_path):
    data = c.frame('calendar_schedule')
    data.iloc[2] = [96, 97, 95, 96, 1]  # opens below the frozen 97 stop
    body = c.post(monkeypatch, tmp_path, 'calendar_schedule', RISK, data=data)
    assert body['trades'] == []
    event = body['raw_report']['calendar_events'][0]
    assert (event['status'], event['reason']) == ('skipped', 'gap_stop_wrong_side')
    assert sizing(body)['rejections'] == [] and sizing(body)['fills'] == []


def test_orb_fill_on_wrong_side_of_frozen_range_rejected(monkeypatch, tmp_path):
    data = c.frame('opening_range_breakout')
    data.iloc[5] = [89., 113., 88., 112., 1.]  # fills below the frozen range low 90
    body = c.post(monkeypatch, tmp_path, 'opening_range_breakout', RISK, data=data)
    assert body['result_status'] == 'success', body.get('error_message')
    assert body['trades'] == []
    assert [r['reason'] for r in sizing(body)['rejections']] == ['stop_wrong_side_of_fill']


def test_red_streak_pricing_key_without_stop_rejected_at_validation(monkeypatch, tmp_path):
    body = c.post(monkeypatch, tmp_path, 'red_streak_rsi', {**RISK, 'take_profit_pct': 3},
                  data=c.frame('red_streak_rsi'))
    assert body['result_status'] == 'failed' and body['error_type'] == 'INVALID_PARAMS'
    assert sizing(body) == {'rejections': [{'reason': 'missing_initial_stop'}]}


def test_pending_list_empty_and_all_single_position_schemas_have_sizing_keys():
    assert p.POSITION_SIZING_PENDING_TOOLS == frozenset()
    for name in c.NAMES:
        assert POSITION_SIZE_KEYS <= set(p.TOOL_SPECS['local.backtesting_py.' + name]['param_schema_properties']), name
    for tool, spec in p.TOOL_SPECS.items():
        if tool not in p.POSITION_SIZING_UNWIRED_TOOLS:
            assert POSITION_SIZE_KEYS <= set(spec['param_schema_properties']), tool
        else:
            assert POSITION_SIZE_KEYS & set(spec['param_schema_properties']) == p.RUNNER_SIZING_ALLOWED_KEYS[tool], tool
