"""Short-only independent rational goldens, causal prefixes and registered provider execution."""
from pathlib import Path
import json
import sys

import numpy as np
import pandas as pd
import pytest
from backtesting import Backtest
from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import cutie_backtesting_provider as p
from strategy_divergence import divergence_signals, macd_values
from strategy_time_layer import TimeConfig, TimeContext
from test_time_layer import DEFAULTS as TIME_OFF

NAMES = ('macd_bearish_divergence', 'rsi_bearish_divergence')


def hand_params(name):
    values = dict(swing_n=2)
    if name.startswith('macd'):
        values.update(fast=2, slow=3, signal=2)
    else:
        values.update(rsi_period=2)
    return values


def hand_frame(size=64):
    # H1=13 High121 Close120, H2=21 High122 Close110, gap8.
    # Right N2 closes at23; MACD cross down23, next-open fill100 at24.
    closes = [100.]*12+[110,120,110,105,104,104,106,108,109,110,111,106,106,90,90,90]
    closes += [90.]*(size-len(closes))
    data = pd.DataFrame(dict(Open=closes, High=np.array(closes)+1, Low=np.array(closes)-1,
                             Close=closes, Volume=100.),
                        index=pd.date_range('2026-01-01', periods=size, freq='h'))
    data.iloc[21, 1] = 122.
    data.iloc[24, 0] = 100.
    data.iloc[24, 2] = 99.
    return data


def run(name, data=None, *, warm=0, **values):
    data = hand_frame() if data is None else data
    cls = p.TOOL_SPECS['local.backtesting_py.'+name]['build']({**hand_params(name), **values})['strategy']
    cls._warmup_bars = warm
    cls._warmup_cols = {c: data[c].iloc[:warm].to_numpy() for c in p._WARMUP_COLUMNS}
    main = data.iloc[warm:].copy()
    if cls._time_config is not None:
        cls._time_context = TimeContext.build(cls._time_config, '1h', main.index)
    return Backtest(main, cls, cash=100000, exclusive_orders=True, finalize_trades=True).run()


def facts(data=None, *, kind='macd', values=None, dif=None, dea=None, **config):
    data = hand_frame() if data is None else data
    # Test doubles are scalar, fixed indicator facts, never generated by subject.
    if values is None:
        values = [40.]*max(24,len(data))
        values[13], values[21] = (90., 80.) if kind=='rsi' else (3., 1.)
    if dif is None:
        dif = [1.]*len(data)
        dif[23:] = [-1.]*(len(data)-23)
    dea = [0.]*len(data) if dea is None else dea
    return divergence_signals(*(data[c].to_numpy() for c in ('High','Low','Close')), values,
                              kind=kind, n=2, dif=dif, dea=dea, direction="short", **config)


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('warm', [0, 10])
def test_hand_high_bar_values_and_next_open(name, warm):
    result = run(name, warm=warm)
    entries = result['_strategy'].divergence_report['entries']
    assert len(entries) == 1
    assert entries[0] == dict(setup=0, entry_bar=24-warm, entry_price=100.,
                             frozen_stop=pytest.approx(122.122), frozen_target=pytest.approx(55.756))
    setup = result['_strategy'].divergence_report['setups'][0]
    assert (setup['h1_index'], setup['h2_index'], setup['confirmed_at'], setup['signal_bar']) == (13,21,23,23)
    assert (setup['h1_price'], setup['h2_price']) == (121.,122.)
    if name.startswith('macd'):
        assert setup['h1_indicator'] == pytest.approx(55/18)
        assert setup['h2_indicator'] == pytest.approx(.5218417318138364)
        assert result['_trades'][['EntryBar','ExitBar']].values.tolist() == [[24-warm,28-warm]]
    else:
        assert setup['h1_indicator'] == 100
        assert setup['h2_indicator'] == pytest.approx(92.48826291079812)
        assert result['_trades'][['EntryBar','ExitBar']].values.tolist() == [[24-warm,25-warm]]


@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_unconfirmed_second_high_never_signals_and_prefix_is_causal(kind):
    data = hand_frame()
    dif = [1.]*len(data)
    dif[22] = -1.  # Early cross one bar before H2's right N bars have closed.
    dif[24:] = [-1.]*(len(data)-24)
    full, _ = facts(data, kind=kind, dif=dif)
    assert all(full[i] is None for i in (21,22))
    assert full[23 if kind=='rsi' else 24] is not None
    for end in (21,22,23,24,25,29):
        part, _ = facts(data.iloc[:end], kind=kind, dif=dif[:end])
        assert part == full[:end]
    changed = data.copy()
    changed.iloc[25:, :4] = [500,501,499,500]
    assert facts(changed, kind=kind, dif=dif)[0][:25] == full[:25]


@pytest.mark.parametrize('name', NAMES)
def test_registered_short_prefix_cannot_enter(name):
    assert run(name, hand_frame().iloc[:23])['_trades'].empty
    assert run(name, hand_frame().iloc[:24])['_trades'].empty  # no next Open
    assert run(name, hand_frame().iloc[:25])['_strategy'].divergence_report['entries'][0]['entry_bar'] == 24


@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_samples_high_bar_not_confirmation_bar(kind):
    values = [0.]*64
    values[13],values[21] = 90.,80.
    values[15],values[23] = 1.,90.  # confirmation samples would reverse divergence
    assert facts(kind=kind, values=values)[0][23] is not None


@pytest.mark.parametrize('high,valid', [(122.,True),(121.,False),(120.,False)])
@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_price_direction_strict(high,valid,kind):
    data=hand_frame();data.iloc[21,1]=high
    assert (facts(data,kind=kind)[0][23] is not None) is valid


@pytest.mark.parametrize('second,valid', [(91.,False),(90.,False),(89.,True)])
@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_indicator_direction_strict(second,valid,kind):
    values=[40.]*64;values[13],values[21]=90.,second
    assert (facts(kind=kind,values=values)[0][23] is not None) is valid


@pytest.mark.parametrize('first,valid', [(65.001,True),(65.,False),(64.999,False)])
def test_rsi_threshold_strict(first,valid):
    values=[40.]*64;values[13],values[21]=first,60.
    assert (facts(kind='rsi',values=values)[0][23] is not None) is valid


@pytest.mark.parametrize('lo,hi,valid', [(8,8,True),(9,60,False),(5,7,False)])
def test_gap_bounds_inclusive(lo,hi,valid):
    assert (facts(min_gap=lo,max_gap=hi)[0][23] is not None) is valid


def test_adjacent_high_only():
    data=hand_frame();data.iloc[17,1]=121.5
    assert not any(facts(data)[0])  # gaps4 to new adjacent highs fail minimum5


def test_close_invalidation_before_later_macd_cross():
    data=hand_frame();data.iloc[24,:4]=[120,124,119,123]
    dif=[1.]*64;dif[25:]=[-1.]*39
    signals,setups=facts(data,dif=dif)
    assert not any(signals)
    assert setups[0]['status']=='invalidated_close' and setups[0]['invalidated_at']==24
    data.iloc[24,:4]=[120,123,119,122*1.001]  # equality does not invalidate
    assert facts(data,dif=dif)[0][25] is not None


def test_new_confirmed_high_invalidates_waiting_macd():
    data=hand_frame();data.iloc[24,:4]=[110,121.5,109,110]
    data.iloc[25,:4]=[110,111,109,110];data.iloc[26,:4]=[110,111,109,110]
    dif=[1.]*64;dif[27:]=[-1.]*37
    signals,setups=facts(data,dif=dif)
    assert not any(signals)
    assert setups[0]['status']=='invalidated_new_high' and setups[0]['invalidated_at']==26


@pytest.mark.parametrize('compare', ['dif','hist'])
def test_macd_comparison_modes(compare):
    report=run(NAMES[0],compare=compare)['_strategy'].divergence_report
    assert len(report['entries'])==1 and report['compare']==compare
    if compare=='hist':
        assert report['setups'][0]['h1_indicator']==pytest.approx(35/27)
        assert report['setups'][0]['h2_indicator']==pytest.approx(.0848256276919781)


def test_independent_indicator_goldens_and_causal_tail():
    dif,dea,hist=macd_values([100.,110.,120.,110.],2,3,2)
    np.testing.assert_allclose(dif,[0,5/3,55/18,65/108],atol=1e-12)
    np.testing.assert_allclose(dea,[0,10/9,65/27,65/54],atol=1e-12)
    np.testing.assert_allclose(hist,[0,10/9,35/27,-65/54],atol=1e-12)
    np.testing.assert_allclose(p._rsi_series([100.,110.,120.,110.],2),[50,100,100,50])
    data=hand_frame()
    before=macd_values(data.Close,2,3,2)
    data.iloc[25:,3]=10000
    after=macd_values(data.Close,2,3,2)
    for a,b in zip(before,after):np.testing.assert_array_equal(a[:25],b[:25])


@pytest.mark.parametrize('name', NAMES)
def test_2r_uses_actual_fill_and_remains_frozen(name):
    data=hand_frame();data.iloc[25,:4]=[90,91,56.,90]
    data.iloc[26,:4]=[90,91,55.,90]
    # Signal close106 would target73.756; actual fill100 gives55.756.
    result=run(name,data,**({'rsi_exit_below':0} if name.startswith('rsi') else {}))
    assert result['_trades'][['EntryBar','ExitBar']].values.tolist()==[[24,27]]
    assert result['_strategy'].divergence_report['exits']==[dict(reason='take_profit',decision_bar=26)]
    assert result['_strategy'].divergence_report['entries'][0]['frozen_target']==pytest.approx(55.756)


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('opening,valid', [(122.2,False),(122.122,False),(122.121,True)])
def test_next_open_gap_is_skipped_once(name,opening,valid):
    data=hand_frame();data.iloc[24,:4]=[opening,123.,99.,106.]
    report=run(name,data)['_strategy'].divergence_report
    assert bool(report['entries']) is valid
    assert bool(report['skipped_entries']) is not valid
    if not valid:assert report['skipped_entries'][0]['reason']=='entry_open_at_or_above_frozen_stop'


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('stop,expiry,reason', [(True,True,'stop_loss'),(False,True,'time_expiry'),(False,False,'take_profit')])
def test_same_bar_exit_priority(name,stop,expiry,reason):
    data=hand_frame();data.iloc[24,:4]=[100,123. if stop else 110.,50,106]
    result=run(name,data,**({'max_holding_bars':1,'risk_layer_enabled':True} if expiry else {}))
    assert result['_trades'][['EntryBar','ExitBar']].values.tolist()==[[24,25]]
    assert result['_strategy'].divergence_report['exits'][0]['reason']==reason


@pytest.mark.parametrize('name', NAMES)
def test_time_blocks_pair_without_delayed_entry(name):
    assert not run(name,time_layer_enabled=True,time_session_start='01:00',time_session_end='02:00')['_strategy'].divergence_report['entries']


@pytest.mark.parametrize('name', NAMES)
def test_default_off_engine_bytes_equal(name):
    a=run(name);b=run(name,**TIME_OFF)
    pd.testing.assert_frame_equal(a['_trades'],b['_trades'])
    pd.testing.assert_frame_equal(a['_equity_curve'],b['_equity_curve'])
    assert a['_strategy'].divergence_report==b['_strategy'].divergence_report


def request(name,params,data=None):
    data=hand_frame() if data is None else data
    return dict(backtest=dict(run_id='9t4',provider_tool_id='local.backtesting_py.'+name,
        provider_params=params,symbol='BTCUSDT',market='futures',timeframe='1h',
        start_at=int(data.index[0].timestamp()),end_at=int(data.index[-1].timestamp())+3600,
        initial_capital='10000',fee_bps='0',slippage_bps='0'))


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('values', [dict(direction='long'),dict(direction='both'),dict(swing_n=True),dict(swing_n=2.0),
    dict(min_gap_bars=10,max_gap_bars=5),dict(swing_n=0),dict(min_gap_bars='5'),
    dict(stop_loss_pct=1),dict(take_profit_pct=2),dict(risk_layer_enabled=True,trailing_stop_pct=1)])
def test_invalid_params_rejected_before_fetch(name,values,monkeypatch):
    monkeypatch.setattr(p,'AUTH_TOKEN','')
    monkeypatch.setattr(p,'_fetch_ohlcv',lambda *a:pytest.fail('invalid request fetched'))
    monkeypatch.setattr(p,'_fetch_template_warmup',lambda *a:pytest.fail('invalid request fetched warmup'))
    assert TestClient(p.app).post('/cutie/backtest',json=request(name,values)).json()['error_type']=='INVALID_PARAMS'
    with pytest.raises(ValueError,match='INVALID_PARAMS'):p.TOOL_SPECS['local.backtesting_py.'+name]['build'](values)


@pytest.mark.parametrize('name,values', [(NAMES[0],dict(fast=3,slow=3)),(NAMES[0],dict(compare='bad')),
    (NAMES[0],dict(signal=2.0)),(NAMES[1],dict(rsi_period=2.0)),(NAMES[1],dict(rsi_first_above=20,rsi_exit_below=30))])
def test_indicator_validation(name,values):
    with pytest.raises(ValueError,match='INVALID_PARAMS'):p.TOOL_SPECS['local.backtesting_py.'+name]['build'](values)


@pytest.mark.parametrize('name', NAMES)
def test_http_raw_details_and_frozen_result_v2_keys(name,monkeypatch,tmp_path):
    data=hand_frame()
    monkeypatch.setattr(p,'AUTH_TOKEN','')
    monkeypatch.setattr(p,'REPORTS_DIR',tmp_path)
    monkeypatch.setattr(p,'_fetch_ohlcv',lambda *a:data.copy())
    requested = []
    def warmup(*args):
        requested.append(args[5])
        return data.iloc[:0].copy()
    monkeypatch.setattr(p,'_fetch_template_warmup',warmup)
    monkeypatch.setattr(Backtest,'plot',lambda *a,**kw:None)
    result=TestClient(p.app).post('/cutie/backtest',json=request(name,hand_params(name))).json()
    assert result['result_status']=='success',result
    assert requested == [76 if name.startswith('macd') else 71]
    assert len(result['trades'])==1
    assert result['raw_report']['divergence']['setups'][0]['h2_index']==21
    assert result['raw_report']['divergence']['entries'][0]['frozen_target']==pytest.approx(55.756)
    assert result['assumptions']['divergence_execution']['indicator_sample']=='swing_high_bar'
    # Independent frozen contract baseline, not a key set derived from new response.
    assert set(result['metrics'])=={'total_return','max_drawdown','trade_count'}
    assert set(result['trades'][0])=={'seq','opened_at','closed_at','side','qty','entry_price','exit_price','fee','slippage','pnl'}
    for node in ('metrics','equity_curve','trades','data_manifest'):
        assert 'divergence' not in str(result[node])


@pytest.mark.parametrize('gap,valid', [(4,False),(5,True),(60,True),(61,False)])
@pytest.mark.parametrize('kind', ['macd','rsi'])
def test_default_gap_endpoints_hand_sequence(gap,valid,kind):
    size=gap+15
    high=[101.]*size;high[10],high[10+gap]=110.,111.
    values=[50.]*size;values[10],values[10+gap]=90.,80.
    dif=[1.]*size;dif[11+gap:]=[-1.]*(size-11-gap)
    signals,_=divergence_signals(high,[99.]*size,[100.]*size,values,
        kind=kind,n=1,dif=dif,dea=[0.]*size,direction='short')
    assert (signals[11+gap] is not None) is valid


@pytest.mark.parametrize('name', NAMES)
def test_underwarmed_first_high_cannot_arm(name):
    # MACD indicator warmup slow3*3+signal2+1=12; RSI period2*3+1=7.
    # Move our first swing into the underwarmed prefix; later H2 stays eligible.
    first=10 if name.startswith('macd') else 5
    data=hand_frame().iloc[13-first:].copy()
    assert not run(name,data)['_strategy'].divergence_report['entries']


@pytest.mark.parametrize('name', NAMES)
def test_time_flatten_beats_target(name):
    data=hand_frame();data.iloc[24,2]=50.
    result=run(name,data,time_layer_enabled=True,time_flatten_at='01:00')
    # Flatten clock: bar24's close reaches01:00; entry Open00:00 exists first.
    assert result['_strategy'].divergence_report['exits'][0]['reason']=='time_expiry'
    assert result['_trades'][['EntryBar','ExitBar']].values.tolist()==[[24,25]]


def test_rsi_exit_threshold_strict_and_next_open(monkeypatch):
    values=[50.]*64;values[13],values[21]=90.,80.
    values[24],values[25]=30.,29.
    monkeypatch.setattr(p,'_rsi_series',lambda *a:np.array(values))
    result=run(NAMES[1])
    assert result['_trades'][['EntryBar','ExitBar']].values.tolist()==[[24,26]]
    assert result['_strategy'].divergence_report['exits']==[dict(reason='rsi_exit',decision_bar=25)]


@pytest.mark.parametrize('name', NAMES)
def test_http_off_bytes_and_gap_reason(name,monkeypatch,tmp_path):
    data=hand_frame()
    monkeypatch.setattr(p,'AUTH_TOKEN','')
    monkeypatch.setattr(p,'REPORTS_DIR',tmp_path)
    monkeypatch.setattr(p,'_fetch_ohlcv',lambda *a:data.copy())
    monkeypatch.setattr(p,'_fetch_template_warmup',lambda *a:data.iloc[:0].copy())
    monkeypatch.setattr(Backtest,'plot',lambda *a,**kw:None)
    client=TestClient(p.app)
    original=client.post('/cutie/backtest',json=request(name,hand_params(name))).json()
    explicit=client.post('/cutie/backtest',json=request(name,{**hand_params(name),**TIME_OFF})).json()
    for key in ('schema_version','metrics','trades','equity_curve','data_manifest','assumptions','raw_report'):
        assert json.dumps(original[key],sort_keys=True,separators=(',',':'))==json.dumps(explicit[key],sort_keys=True,separators=(',',':')),key
    data.iloc[24,0]=122.2
    gap=client.post('/cutie/backtest',json=request(name,hand_params(name))).json()
    assert gap['result_status']=='success' and not gap['trades']
    assert gap['raw_report']['divergence']['skipped_entries'][0]['reason']=='entry_open_at_or_above_frozen_stop'


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('market', ['spot', None])
@pytest.mark.parametrize('direction', [None, 'short', 'long', 'both'])
def test_futures_only_before_any_fetch(name,market,direction,monkeypatch):
    monkeypatch.setattr(p,'AUTH_TOKEN','')
    monkeypatch.setattr(p,'_fetch_ohlcv',lambda *a:pytest.fail('market gate fetched'))
    monkeypatch.setattr(p,'_fetch_template_warmup',lambda *a:pytest.fail('market gate fetched warmup'))
    body=request(name,{} if direction is None else {'direction':direction})
    if market is None:
        body['backtest'].pop('market')
    else:
        body['backtest']['market']=market
    assert TestClient(p.app).post('/cutie/backtest',json=body).json()['error_type']=='INVALID_PARAMS'


@pytest.mark.parametrize('name', NAMES)
def test_unwired_filter_rejected_and_not_executed(name,monkeypatch):
    properties=p.TOOL_SPECS['local.backtesting_py.'+name]['param_schema_properties']
    assert not any(key.startswith('filter_') for key in properties)
    monkeypatch.setattr(p._FixedRiskMixin,'_filter_allow_entry',lambda *a:pytest.fail('unwired filter gate called'))
    assert run(name)['_strategy'].divergence_report['entries']
    with pytest.raises(ValueError,match='INVALID_PARAMS'):
        p.TOOL_SPECS['local.backtesting_py.'+name]['build']({'filter_layer_enabled':True})


def http_response(name,params=None,data=None,warm=0):
    from unittest.mock import patch
    import tempfile
    data=hand_frame() if data is None else data
    main=data.iloc[warm:].copy()
    with tempfile.TemporaryDirectory(prefix='shortpat2-') as reports, \
         patch.object(p,'AUTH_TOKEN',''), patch.object(p,'REPORTS_DIR',Path(reports)), \
         patch.object(p,'_fetch_ohlcv',lambda *a:main.copy()), \
         patch.object(p,'_fetch_template_warmup',lambda *a:data.iloc[:warm].copy()), \
         patch.object(Backtest,'plot',return_value=None):
        result=TestClient(p.app).post('/cutie/backtest',json=request(name,{**hand_params(name),**(params or {})},main)).json()
    assert result['result_status']=='success',result
    return result


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('case', ['liquidation','closer_stop','gap_liquidation'])
def test_short_isolated_risk_arbitration_and_accounting(name,case):
    from decimal import Decimal
    data=hand_frame()
    # Fill100, leverage5 => short liquidation120, frozen stop122.122 beyond it.
    if case=='gap_liquidation':
        data.iloc[25,:4]=[130,131,129,130]
    else:
        data.iloc[24,:4]=[100,125,99,106]
    leverage=2 if case=='closer_stop' else 5
    result=http_response(name,dict(leverage=leverage,position_size_pct=10,**({'rsi_exit_below':0} if name.startswith('rsi') else {})),data)
    risk=result['raw_report']['isolated_risk']
    assert result['trades'][0]['side']=='short'
    if case=='closer_stop':
        # L2 liquidation150; closer122.122 stop wins, settled at next open90.
        assert risk['liquidation_count']==0
        assert result['raw_report']['divergence']['exits'][0]['reason']=='stop_loss'
        assert result['trades'][0]['exit_price']=='90'
    else:
        price='130' if case=='gap_liquidation' else '120'
        assert risk['liquidation_count']==1
        assert result['trades'][0]['exit_price']==price
        assert risk['liquidations'][0]['liquidation_gap'] is (case=='gap_liquidation')
    trade=result['trades'][0]
    entry,exit,qty=(Decimal(trade[k]) for k in ('entry_price','exit_price','qty'))
    assert Decimal(trade['fee'])==0 and Decimal(trade['slippage'])==0
    assert Decimal(trade['pnl'])==(entry-exit)*qty
    assert Decimal(result['equity_curve'][-1]['equity'])==Decimal('10000')+Decimal(trade['pnl'])
    assert Decimal(result['metrics']['total_return'])==Decimal(trade['pnl'])/Decimal('10000')
    for price_key,time_key in (('entry_price','opened_at'),('exit_price','closed_at')):
        bar=data.loc[pd.Timestamp(trade[time_key],unit='s')]
        assert Decimal(str(bar.Low))<=Decimal(trade[price_key])<=Decimal(str(bar.High))
    assert 'funding' in str(result['assumptions']).lower()


@pytest.mark.parametrize('name', NAMES)
@pytest.mark.parametrize('warm', [0,10])
@pytest.mark.parametrize('explicit', [False,True])
def test_branch_head_isolated_off_golden(name,warm,explicit):
    from canonical_json import canonical_json
    import hashlib
    fixture=json.loads((Path(__file__).parent/'fixtures/shortpat2_isolated_off.json').read_text())
    params={'leverage':1,**TIME_OFF} if explicit else {}
    body=http_response(name,params,warm=warm)
    assert body['trades']
    assert 'isolated_risk' not in body['raw_report']
    assert 'isolated_margin' not in body['assumptions']
    v2={key:body[key] for key in ('schema_version','metrics','trades','equity_curve','data_manifest')}
    actual={'v2':hashlib.sha256(canonical_json(v2).encode()).hexdigest()}
    for key in ('assumptions','raw_report'):
        actual[key]=hashlib.sha256(json.dumps(body[key],sort_keys=True,separators=(',',':')).encode()).hexdigest()
    assert actual==fixture['cases'][name+'/'+str(warm)]


def test_catalog_count_and_default_params():
    # 集成 D：做空二基于 main 32ae030（48 个）+2 = 50；同批合入 10-E 轮动 +1、做空一 +2 → 53
    assert len(p.TOOL_SPECS)==53
    for name in NAMES:
        assert p.TOOL_SPECS['local.backtesting_py.'+name]['markets']==['futures']
        props=p.TOOL_SPECS['local.backtesting_py.'+name]['param_schema_properties']
        assert props['direction']==dict(type='string',default='short',enum=['short'])
        assert props['swing_n']['default']==5
        assert props['min_gap_bars']['default']==5 and props['max_gap_bars']['default']==60
    assert p.TOOL_SPECS['local.backtesting_py.'+NAMES[0]]['param_schema_properties']['compare']['default']=='dif'


@pytest.mark.parametrize('kind', ['macd','rsi'])
@pytest.mark.parametrize('warm', [0,10])
def test_bullish_response_bytes_match_original_engine(kind,warm,monkeypatch):
    import subprocess
    import types
    import strategy_divergence as engine
    from test_9t4_divergence import hand_frame as long_frame
    name=kind+'_bullish_divergence'
    data=long_frame()
    main=data.iloc[warm:].copy()
    monkeypatch.setattr(p,'AUTH_TOKEN','')
    monkeypatch.setattr(p,'_fetch_ohlcv',lambda *a:main.copy())
    monkeypatch.setattr(p,'_fetch_template_warmup',lambda *a:data.iloc[:warm].copy())
    monkeypatch.setattr(Backtest,'plot',lambda *a,**kw:None)
    import tempfile
    with tempfile.TemporaryDirectory(prefix='shortpat2-long-') as reports:
        monkeypatch.setattr(p,'REPORTS_DIR',Path(reports))
        body=request(name,hand_params(name),main)
        body['backtest']['market']='spot'
        client=TestClient(p.app)
        current=client.post('/cutie/backtest',json=body).json()
        assert current['result_status']=='success' and current['trades']
        source=subprocess.check_output(['git','show','32ae030:backtesting-py/strategy_divergence.py'],text=True)
        original=types.ModuleType('shortpat2_original_divergence')
        monkeypatch.setitem(sys.modules,original.__name__,original)
        exec(compile(source,engine.__file__,'exec'),original.__dict__)
        monkeypatch.setattr(engine,'make_divergence_strategy',original.make_divergence_strategy)
        before=client.post('/cutie/backtest',json=body).json()
    for key in ('schema_version','metrics','trades','equity_curve','data_manifest','assumptions','raw_report'):
        assert json.dumps(current[key],sort_keys=True,separators=(',',':'))==json.dumps(before[key],sort_keys=True,separators=(',',':')),key


def test_bullish_builders_and_catalog_source_bytes_unchanged():
    import subprocess
    import ast
    original=subprocess.check_output(['git','show','32ae030:backtesting-py/cutie_backtesting_provider.py'],text=True)
    current=Path(p.__file__).read_text()
    def sections(source):
        result={}
        for node in ast.walk(ast.parse(source)):
            if isinstance(node,ast.FunctionDef) and node.name in ('_build_divergence','_build_macd_bullish_divergence','_build_rsi_bullish_divergence'):
                start=min([node.lineno]+[d.lineno for d in node.decorator_list])
                result[node.name]=''.join(source.splitlines(keepends=True)[start-1:node.end_lineno])
            if isinstance(node,ast.Dict):
                for key,value in zip(node.keys,node.values):
                    if isinstance(key,ast.Constant) and key.value in ('local.backtesting_py.macd_bullish_divergence','local.backtesting_py.rsi_bullish_divergence'):
                        result[key.value]=ast.get_source_segment(source,value)
        return result
    assert len(sections(current))==5
    assert sections(current)==sections(original)
